x-content-service: &content-service
  build: ./content-management-service
  environment:
    - CM_DB_USER=postgres
    - CM_DB_PASS=postgres
    - CM_DB_HOST=postgres
    - CM_DB_PORT=5432
    - REDIS_HOST=redis:6379
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
  depends_on:
    - postgres
    - redis
    - rabbitmq
  restart: unless-stopped

x-postgres-client: &postgres-client
  depends_on:
    - postgres
  restart: unless-stopped

services:
  frontend:
    build: ./ui-service
    ports:
      - "3009:80"
    restart: unless-stopped

  api-gateway:
    build: ./api-gateway
    ports:
      - 8888:80
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - user-service
      - content-management-service
      - content-documents
    restart: unless-stopped

  content-management-service:
    <<: *content-service
    volumes:
      - files:/app/files

  content-documents:
    <<: *content-service
    build:
      context: ./content-management-service
      dockerfile: Dockerfile.documents
    volumes:
      - files:/app/files

  celery-worker:
    <<: *content-service
    depends_on:
      - redis
      - content-management-service
    command: celery -A shared.celery_app worker --loglevel info

  user-events-consumer:
    <<: *content-service
    depends_on:
      - rabbitmq
      - content-management-service
    volumes:
      - files:/app/files
    command: python run_consumer.py

  user-service:
    <<: *postgres-client
    build: ./user-service
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - postgres
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.13-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  rabbitmq:
  redis-data:
  files:
  postgres:
