services:
  frontend:
    build: ./ui-service
    ports:
      - "3009:80"
    restart: unless-stopped

  kong:
    image: kong:3.9
    ports:
      - 8888:8000
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
    volumes:
      - ./api-gateway/kong.yml:/kong/kong.yml
    restart: unless-stopped

  file-processor-service:
    build: ./file-processor-service
    environment:
      - REDIS_HOST=redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CONTENT_MANAGEMENT_SERVICE=http://content-management-service:8000
      #- CLAMD_HOST=clamav
      - CLAMD_PORT=3310
    volumes:
      - files:/app/files
    depends_on:
      - postgres
      - content-management-service
      #- clamav
    restart: unless-stopped

  content-management-service:
    build: ./content-management-service
    environment:
      - CM_DB_USER=postgres
      - CM_DB_PASS=postgres
      - CM_DB_HOST=postgres
      - CM_DB_PORT=5432
      - SCHEDULER_SERVICE=http://scheduler-service:8000
    volumes:
      - files:/app/files
    depends_on:
      - postgres
    restart: unless-stopped

  user-service:
    build: ./user-service
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres
    restart: unless-stopped

  scheduler-service:
    build: ./scheduler-service
    environment:
      - MONGODB_HOST=mongodb:27017
    depends_on:
      - mongodb
    restart: unless-stopped

  redis:
    image: redis:6.2
    volumes:
      - redis-data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    restart: unless-stopped

  celery-worker:
    build: ./file-processor-service
    environment:
      - REDIS_HOST=redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CONTENT_MANAGEMENT_SERVICE=http://content-management-service:8000
    depends_on:
      - redis
      - file-processor-service
    command: >
      celery -A app
      worker
      --loglevel info
    restart: unless-stopped

  # clamav:
  #   image: mkodockx/docker-clamav:alpine
  #   restart: unless-stopped

volumes:
  redis-data:
  files:
  postgres:
  mongodb: