services:
  kong:
    image: kong:3.9
    ports:
      - 8888:8000
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_LOG_LEVEL: debug
    volumes:
      - ./api-gateway/kong.yml:/kong/kong.yml

  file-processor-service:
    build: ./file-processor-service
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CONTENT_MANAGEMENT_SERVICE=http://content-management-service:8000
    volumes:
      - files:/app/files
    depends_on:
      - postgres
      - content-management-service

  content-management-service:
    build: ./content-management-service
    ports:
      - "8001:8000"
    environment:
      - CM_DB_USER=postgres
      - CM_DB_PASS=postgres
      - CM_DB_HOST=postgres
      - CM_DB_PORT=5432
      - SCHEDULER_SERVICE=http://scheduler-service:8000
    depends_on:
      - postgres

  user-service:
    build: ./user-service
    ports:
      - "8002:8000"
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

  scheduler-service:
    build: ./scheduler-service
    ports:
      - "8003:8000"
    environment:
      - MONGODB_HOST=mongodb:27017
    depends_on:
      - mongodb

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5450:5432"

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"

  celery-worker:
    build: ./file-processor-service
    environment:
      - REDIS_HOST=redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CONTENT_MANAGEMENT_SERVICE=http://content-management-service:8000
    depends_on:
      - redis
      - file-processor-service
    command: >
      celery -A app
      worker
      --loglevel info

volumes:
  redis-data:
  files:
  postgres:
  mongodb: