from srp_infrastructure_effects import (
    FILESYSTEM_OPERATIONS,
    FILESYSTEM_PREFIXES,
    NETWORK_OPERATIONS,
    NETWORK_PREFIXES,
    PERSISTENCE_OPERATIONS,
    PERSISTENCE_PREFIXES,
    PROCESS_OPERATIONS,
    PROCESS_PREFIXES,
    QUEUE_OPERATIONS,
    QUEUE_PREFIXES,
)
from srp_interface_effects import (
    AI_OPERATIONS,
    AI_PREFIXES,
    AUTHENTICATION_OPERATIONS,
    AUTHENTICATION_PREFIXES,
    EMAIL_OPERATIONS,
    EMAIL_PREFIXES,
    PRESENTATION_OPERATIONS,
    PRESENTATION_PREFIXES,
)

EFFECT_RULES = (
    ("ai", AI_PREFIXES, AI_OPERATIONS),
    ("authentication", AUTHENTICATION_PREFIXES, AUTHENTICATION_OPERATIONS),
    ("email", EMAIL_PREFIXES, EMAIL_OPERATIONS),
    ("filesystem", FILESYSTEM_PREFIXES, FILESYSTEM_OPERATIONS),
    ("network", NETWORK_PREFIXES, NETWORK_OPERATIONS),
    ("persistence", PERSISTENCE_PREFIXES, PERSISTENCE_OPERATIONS),
    ("presentation", PRESENTATION_PREFIXES, PRESENTATION_OPERATIONS),
    ("process", PROCESS_PREFIXES, PROCESS_OPERATIONS),
    ("queue", QUEUE_PREFIXES, QUEUE_OPERATIONS),
)
