from types import TracebackType

class BasicProperties:
    def __init__(self, delivery_mode: int = ...) -> None: ...

class URLParameters:
    def __init__(self, url: str) -> None: ...

class Channel:
    def confirm_delivery(self) -> None: ...
    def exchange_declare(
        self, *, exchange: str, exchange_type: str, durable: bool = ...
    ) -> None: ...
    def queue_declare(self, *, queue: str, durable: bool = ...) -> None: ...
    def queue_bind(
        self, *, queue: str, exchange: str, routing_key: str
    ) -> None: ...
    def basic_publish(
        self,
        *,
        exchange: str,
        routing_key: str,
        body: bytes,
        properties: BasicProperties = ...,
    ) -> None: ...
    def basic_consume(
        self, *, queue: str, on_message_callback: object
    ) -> None: ...
    def basic_ack(self, *, delivery_tag: int) -> None: ...
    def start_consuming(self) -> None: ...

class BlockingConnection:
    def __init__(self, parameters: URLParameters) -> None: ...
    def __enter__(self) -> BlockingConnection: ...
    def __exit__(
        self,
        exception_type: type[BaseException] | None,
        exception: BaseException | None,
        traceback: TracebackType | None,
    ) -> None: ...
    def channel(self) -> Channel: ...
    def close(self) -> None: ...

class DeliveredMessage:
    @property
    def delivery_tag(self) -> int: ...
